### ISSUE TITLE
Light/Dark theme

### ISSUE THREAD

**Issue by DimaPidko** [DimaPidko/chatter#28]
Will into User Profile
Add save to localStorage

**Comment by Avinashshiyani** [comment]
I can help you in this too @DimaPidko

**Comment by DimaPidko** [comment]
This task i want do myself

**Comment by DimaPidko** [comment]
If you want, you can do User Profile...
But we need create style for User Profile Page

**Comment by DimaPidko** [comment]
Like:
Name - 
Age - 
Email - 
registration date - 
etc...

**Comment by Avinashshiyani** [comment]
> Like:
> Name - 
> Age - 
> Email - 
> registration date - 
> etc...
> 

Ok then I will make this user profile page 😇
