### ISSUE TITLE
Add React-Form

### ISSUE THREAD

**Issue by DimaPidko** [DimaPidko/chatter#29]

**Comment by Avinashshiyani** [comment]
I can add react form as you wanted please add some description so I can work

**Comment by DimaPidko** [comment]
I need put in Register and Login page`s - React Form. Validation

**Comment by Avinashshiyani** [comment]
i will put it... assign me

**Comment by Avinashshiyani** [comment]
Thanks for assigning me this task I will add form validation to this project
